from enum import IntEnum

class MessageType(IntEnum):
    MSG_TYPE_CHAT_TEXT = 1
    MSG_TYPE_FILE_INFO = 10
    MSG_TYPE_FILE_CHUNK = 11
    MSG_TYPE_FILE_END = 12
    MSG_TYPE_FILE_REQUEST = 13,
    MSG_TYPE_USER_LOGIN_REQUEST = 100
    MSG_TYPE_USER_LOGIN_RESPONSE = 101
    MSG_TYPE_USER_JOIN_NOTICE = 200
    MSG_TYPE_USER_LEAVE_NOTICE = 201
    MSG_TYPE_SERVER_NOTICE = 202
    MSG_TYPE_ERROR_RESPONSE = 500
    MSG_TYPE_PING = 900
    MSG_TYPE_PONG = 901
